---
AWSTemplateFormatVersion: '2010-09-09'
# Sample CFN YAML to demonstrate creating a DPA validation job
#
# Parameters section contains names that are substituted in the Resources section
# These parameters are the names the resources created in the Data Catalog
Parameters:                                                                                                       
# The name of the job to be created
  CFNJobName:  
    Type: String
    Default: dpa-validate-job
    Description: "The name of the job to be created"
# The S3 path where the script for this job is located
  CFNScriptLocation:  
    Type: String
    Default: s3://gl-dpa-dqva/scripts/spark_validate_job.py
    Description: "The S3 path where the script for this job is located"
# The S3 path where the python packages for this job is located
  CFNPythonLibs:  
    Type: String
    Default: s3://gl-dpa-dqva-bin/libs/dpa_fwk-1.2.0-min-py3-none-any.whl
    Description: "The S3 path where the python packages for this job is located"
# The S3 path where the temp data and logs of this job will be stored
  CFNGlueAssetsS3Home:
    Type: String
    MinLength: "1"
    Description: "The S3 path where the temp data and logs of this job will be stored"
    Default: aws-glue-assets-123456789000-us-east-2
#
#
# Resources section defines metadata for the Data Catalog
Resources:
  CFNGlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Path: "/"
      Description: "Allow Glue to call AWS services on your behalf"
      RoleName: CFNGlueJobRole

# Create job to run script which validates CSV and Parquet entities in S3
# The script already exists and is called by this job	
  CFNJobDPA:
    Type: AWS::Glue::Job   
    Properties:
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/CFNGlueJobRole  
      DefaultArguments:
        "--job-language": "python"
        "--extra-py-files": !Ref CFNPythonLibs
        "--TempDir": !Sub "s3://${CFNGlueAssetsS3Home}/temporary/"
        "--job-bookmark-option": "job-bookmark-disable"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--enable-spark-ui": "true"
      #Connections:  No connection needed for S3 to S3 job 
      #  ConnectionsList  
      Name: !Ref CFNJobName
      Description: Data Validation Job created with CloudFormation
      LogUri: !Sub "s3://${CFNGlueAssetsS3Home}/sparkHistoryLogs/"
      Command:
        Name: glueetl
        ScriptLocation: !Ref CFNScriptLocation
             # for access to directories use proper IAM role with permission to required buckets and folders
             # script uses temp directory from job definition if required (temp directory not used S3 to S3)
      GlueVersion: 2.0
      NumberOfWorkers: 2
      WorkerType: G.1X
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0


